### ISSUE TITLE
System.FormatException: The format of value '' is invalid.

### ISSUE THREAD

**Issue by AngelMunoz** [fsprojects/FsHttp#109]
Hello there!

I'm trying to make a request like this

```fsharp
#r "nuget: FsHttp"

open FsHttp

http {
    POST "https://api.jspm.io/generate"
    body
    json ("""{
    "install": [ "lodash" ],
    "env": [ "browser", "module" ],
    "graph":true,
    "provider": "jspm"}""")
}
|> Request.send
|> Response.toText
|> printfn "%s"
```
the expected JSON content is the following

```json
{
  "staticDeps": [
    "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
  ],
  "dynamicDeps": [],
  "map": {
    "imports": {
      "lodash": "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
    }
  },
  "graph": {
    "https://ga.jspm.io/npm:lodash@4.17.21/": {
      "lodash.js": {}
    }
  }
}
```
but I get the following instead

```
PS C:\Users\scyth\repos\scripts> dotnet fsi script2.fsx
System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at FsHttp.Request.toAsync@152-4.Invoke(CancellationToken ctok)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528    
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Users\scyth\repos\scripts\script2.fsx:line 6
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```
When I use [nightingale](https://nightingale.rest/) I get this log, not sure if it helps at all
```
Method: POST, RequestUri: 'https://api.jspm.io/generate', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
{
  Content-Type: application/json; charset=utf-8
}

StatusCode: 200, ReasonPhrase: '', Version: 2.0, Content: System.Net.Http.StreamContent, Headers:
{
  Server: Google
  Server: Frontend
  Date: Fri, 30 Sep 2022 00:16:50 GMT
  Access-Control-Allow-Origin: *
  Content-Type: application/json
}
```

Let me know if you need further information

**Comment by RonaldSchlenker** [comment]
Thank you for the issue report. Unfortunately, I cannot reproduce it. If you have further info, please share them. In my test, I use VS2022, .Net SDK 6.0.304 and a plain .fsx file with the content copied from above. 

Could you omit the `|> Response.toText |> printfn "%s"` and just run this in FSI:

```fsharp
#r "nuget: FsHttp"

open FsHttp

http {
    POST "https://api.jspm.io/generate"
    body
    json """
    {
        "install": [ "lodash" ],
        "env": [ "browser", "module" ],
        "graph":true,
        "provider": "jspm"
    }
    """
}
|> Request.send
```

This will print the request, and response + content in the FSI output - like this:

```
REQUEST
--------
POST https://api.jspm.io:443/generate HTTP/1.1
Cookie           : 
Content-Type     : application/json
Content-Length   : 108
===content===
{
    "install": [ "lodash" ],
    "env": [ "browser", "module" ],
    "graph":true,
    "provider": "jspm"}

RESPONSE
---------
HTTP/1.1 200 OK
Access-Control-Allow-Origin   : *
Transfer-Encoding             : chunked
Date                          : Mon, 03 Oct 2022 09:04:37 GMT
Server                        : Google, Frontend
Content-Type                  : application/json

===content===
{
  "staticDeps": [
    "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
  ],
  "dynamicDeps": [],
  "map": {
    "imports": {
      "lodash": "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
    }
  },
  "graph": {
    "https://ga.jspm.io/npm:lodash@4.17.21/": {
      "lodash.js": {}
    }
  }
}
```

**Comment by RonaldSchlenker** [comment]
Thanks for the info. I'll investigate and see if that might be a bug in .Net 7 or if FsHttp is doing something wrong that might have been masked before...

**Comment by Samuel-Dufour** [comment]
Hi,
I added [a PR]( https://github.com/fsprojects/FsHttp/pull/111) that should fix this issue.

**Comment by RonaldSchlenker** [comment]
Thanks for reporting the issue @AngelMunoz and fixing it @Samuel-Dufour :)

I've released  and tested 10.0.0-preview2. See related PR and commits.

**Comment by OnurGumus** [comment]
Hah I also hit this one just now

**Comment by CaptnCodr** [comment]
Yep, me too. 😄 
This fix helped a lot!
